BATCH_SIZE = 32
CLASSES = 2
CLASSIFICATION_THRESHOLD = 0.5
EXPERIMENTAL_EPOCHS = 20
BASELINE_EPOCHS = 20
FINAL_EPOCHS = 30
TEMPERATURE_OPTIMIZATION_STEPS = 100
TEMPERATURE_OPTIMIZATION_LEARNING_RATE = 0.01